### ISSUE TITLE
question for au

### ISSUE THREAD

**Issue by AIXiaoBaiDemon** [HSE-asavchenko/face-emotion-recognition#13]

**Comment by AIXiaoBaiDemon** [comment]
Hello, is there a pre-trained model with AU?

**Comment by HSE-asavchenko** [comment]
I've just uploaded the Tensorflow models from ABAW3 and ABAW4 competitions [here](https://drive.google.com/drive/folders/1WDRa2EhRtVHpzfc8afKaoMlVl4DClZHe?usp=sharing). As I am not sure that they can be successfully used for different datasets, I did not upload the into the main repository. Examples for loading and using these models are available in the [ABAW folder](https://github.com/HSE-asavchenko/face-emotion-recognition/tree/main/src/ABAW)

**Comment by AIXiaoBaiDemon** [comment]
Thank you very much for your reply! The AWAB competition training set may have some preprocessing, and the model prediction is very inaccurate when it is applied to the actual scene, but the model trained by the affectNet you provided is still very accurate in predicting expressions! thank you very much!

**Comment by HSE-asavchenko** [comment]
Thanks! I agree though I believe that my model for EXPR competition in ABAW3 may be potentially used in practice. Closing the issue now
