### ISSUE TITLE
A few suggestions.

### ISSUE THREAD

**Issue by ioctl-user** [HSE-asavchenko/face-emotion-recognition#25]
Hello!

I have a couple of ideas:

1. Could you, please, add text description about difference between models, especially between b0 and b2 general types?
2.  Please consider adding hsemotion-onnx package to the pip repository.

**Comment by HSE-asavchenko** [comment]
Hello!
1. EfficientNet-B0 and B2 are the architectures proposed in an excellent [paper](https://arxiv.org/abs/1905.11946). I just trained them by my own procedure. The main difference is in scaling, b2 accepts an input image with greater resolution(260x260 vs 224x224 from EfficientNet-B0). Moreover, the depth and width, and consequently, the size of EfficientNet-B2 are larger. Hence, it is potentially possible to reach better accuracy, but the latency of EfficientNet-B0 is better. But I should say, that my internal experiments demonstrate that EfficientNet-B0 works better for typical videos. I personally recommend to use [enet_b0_8_best_vgaf.pt](https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/models/affectnet_emotions/enet_b0_8_best_vgaf.pt) or [enet_b0_8_va_mtl.pt](https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/models/affectnet_emotions/enet_b0_8_va_mtl.pt) in practice. These models are typically more accurate for various datasets if you do not want to fine-tune them on new domain
2. Thanks, I will try to do it in 1 or 2 weeks. I'm overwhelmed with a lot of reports now (

**Comment by HSE-asavchenko** [comment]
I created separate hsemotion-onnx package that is available via pip. Moreover, I slightly refactored the code and moved the python packages in the separate repositories: [hsemotion](https://github.com/HSE-asavchenko/hsemotion) and [hsemotion-onnx](https://github.com/HSE-asavchenko/hsemotion-onnx)
