### ISSUE TITLE
Missing enet_b0_8_va_mtl.ptl

### ISSUE THREAD

**Issue by derzhavets-emg** [HSE-asavchenko/face-emotion-recognition#37]
Hi

I am trying to run your Android example. It tries to load file model file "enet_b0_8_va_mtl.ptl", which looks to be missing in the repository.

Is this the file I should generate myself? If yes, I would really appreciate if you can point to the place where this can be done.

Thank you!

**Comment by HSE-asavchenko** [comment]
Hello! Thanks for your interest.
You're correct, the models should be automatically generated. Just run scripts [to_pytorchlite.py](https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/mobile_app/to_pytorchlite.py) and [to_tflite.py](https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/mobile_app/to_tflite.py) from [mobile_app folder](https://github.com/HSE-asavchenko/face-emotion-recognition/tree/main/mobile_app)

**Comment by derzhavets-emg** [comment]
> Hello! Thanks for your interest. You're correct, the models should be automatically generated. Just run scripts [to_pytorchlite.py](https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/mobile_app/to_pytorchlite.py) and [to_tflite.py](https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/mobile_app/to_tflite.py) from [mobile_app folder](https://github.com/HSE-asavchenko/face-emotion-recognition/tree/main/mobile_app)

Thank you!
