### ISSUE TITLE
Request for a demo code

### ISSUE THREAD

**Issue by gd1925** [HSE-asavchenko/face-emotion-recognition#43]
Hi,

Is there a demonstration code available for running videos or webcam feeds? Thank you.

**Comment by gd1925** [comment]
Hi, Thank you very much for your reply. The model is super fast indeed. Runs at >30fps on cpu. Thank you for sharing the code base with us!!

**Comment by HSE-asavchenko** [comment]
Thanks for your positive feedback! Closing the issue

**Comment by timlac** [comment]
I notice that the linked demos limits the number of faces which can be recognized to one. Did you ever do any implementation which can track multiple faces and keep track of the identity of the different faces over time? E.g. assign a face id for each face which is reliable such that the face_id is not mixed up over time.

**Comment by av-savchenko** [comment]
I have an example here
https://github.com/av-savchenko/face-emotion-recognition/blob/main/src/video_summarizer.ipynb

However, for now, I believe it is better to use a special tracker, e.g.
deepsort with face embeddings from insightface. I do not have an example
for such an implementation but it is possible to google it

ср, 2 окт. 2024 г., 20:30 timlac ***@***.***>:
