### ISSUE TITLE
Request for guidelines on training on multitask classification

### ISSUE THREAD

**Issue by gd1925** [HSE-asavchenko/face-emotion-recognition#44]
Hi,

I'm looking to train a custom dataset for multitask classification and I'm interested in trying to train this model. Could you please provide some guidelines or advice on how to proceed with this? Any help would be greatly appreciated!

Thank you.

**Comment by HSE-asavchenko** [comment]
Hello! Please look at the section "Multi-task: FER+Valence-Arousal" at [train_emotions-pytorch.ipynb](https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/src/affectnet/train_emotions-pytorch.ipynb). Section "Multi-task challenge" at [abaw3_train.ipynb](https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/src/ABAW/abaw3_train.ipynb) and [abaw4_mtl_train.ipynb](https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/src/ABAW/abaw4_mtl_train.ipynb) may also help, though in the latter notebook, I actually train three heads separately

**Comment by gd1925** [comment]
Hi @HSE-asavchenko, Thanks a ton for your reply! I will try to see whichever I can understand and try to train using it.
