### ISSUE TITLE
Request for help in the Training Script  for enet_b0_8_best_afew.onnx model

### ISSUE THREAD

**Issue by gd1925** [HSE-asavchenko/face-emotion-recognition#45]
Hello,

I'm reaching out to seek guidance regarding the enet_b0_8_best_afew.onnx model. I'm interested in utilizing this model, but I'm encountering challenges in locating the relevant training script to generate this particular model.

While searching, I came across these scripts: [GitHub Link](https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/src/VGAF_train.ipynb). Additionally, I found that the model is placed under the affectnet folder: [GitHub Link](https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/models/affectnet_emotions/enet_b0_8_best_vgaf.pt).

My understanding is that the model has been trained with EfficientNet B0 using the VGAF dataset, based on the code VGAF_train.ipynb. However, I am unsure if this is the correct procedure or if there are additional steps involved.

Could someone please provide me with more information or guidance on how to properly train and obtain the enet_b0_8_best_afew.onnx model? Any assistance you could offer would be greatly appreciated.

Thank you for your time and support.

**Comment by HSE-asavchenko** [comment]
Hello! All onnx models are simply converted from pytorch using [convert_pt_to_onnx.py](https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/src/convert_pt_to_onnx.py) script. 
All PyTorch models including enet_b0_8_best_afew.pt are trained on AffectNet dataset using [train_faces_torch.ipynb](https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/src/train_faces_torch.ipynb). The models enet_b0_8_best_afew.pt and enet_b0_8_best_vgaf.pt are essentially the same EfficientNet-B0 models trained with the same notebook twice using absolutely the same procedure. You should know that repeating the training will lead to different models. I added suffixes afew and vgaf to distinguish models that extracts features that are more accurate on VGAF and AFEW datasets, see [train_emotions-pytorch-afew-vgaf.ipynb](https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/src/affectnet/train_emotions-pytorch-afew-vgaf.ipynb) for details how to extract features and classify them for these video datasets.

**Comment by gd1925** [comment]
Hi @HSE-asavchenko, that's great!! Thank you for your detailed explanation on my query. Really appreciate it!
