### ISSUE TITLE
about pretrained_faces

### ISSUE THREAD

**Issue by LLFabiann** [HSE-asavchenko/face-emotion-recognition#9]
In the folder "models/pretrained_faces", I can only find a weight file about EfficientNet-B0 which called "state_vggface2_enet0_new.pt", so could you upload the weight file about EfficientNet-B2 which maybe called "state_vggface2_enet2_new.pt" ? Thank you!

**Comment by HSE-asavchenko** [comment]
Thanks for this question, I forgot to upload the state of this model. Right now, the file [state_vggface2_enet2.pt](https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/models/pretrained_faces/state_vggface2_enet2.pt) is available
